/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface MramaCaseSchemaV1 {
  schemaVersion: "1.0";
  meta: {
    slug: string;
    title: string;
    date: string;
    status: "draft" | "published";
    visibility?: "internal" | "public";
    oneLiner: string;
    domain?: string | null;
    tags?: string[];
  };
  problem: {
    summary: string;
    objective: string;
    scale: {
      numVariables: number;
      description: string;
    };
    currentApproach?: string | null;
    constraints?: string[];
    formulation?: string | null;
    objectiveLatex?: string | null;
  };
  improvement: {
    primary: MetricEntry;
    secondary?: MetricEntry[];
  };
  approach: {
    chosen: {
      name: string;
      kind: "classical" | "quantum_inspired" | "quantum_simulated" | "quantum_hardware" | "hybrid";
      rationale: string;
      parameters?: {
        [k: string]: unknown;
      };
      hardware?: string | null;
    };
    alternatives?: {
      name: string;
      kind: "classical" | "quantum_inspired" | "quantum_simulated" | "quantum_hardware" | "hybrid";
      whyNot: string;
    }[];
  };
  reliability?: {
    numRuns: number;
    values: number[];
    median: number;
    min: number;
    max: number;
    successThreshold?: number | null;
    successRate?: number | null;
  };
  optimality?: {
    boundValue: number;
    boundSource: string;
    achievedValue: number;
    gapPercent?: number | null;
    interpretation?: string | null;
  };
  performance?: {
    solveTimeSeconds?: number | null;
    baselineTime?: string | null;
    workUnits?: {
      metric: string;
      value: number;
    } | null;
    note?: string | null;
  };
  value?: {
    items: {
      label: string;
      unitValue: number;
      unitLabel: string;
      quantity: number;
      quantityLabel: string;
      annualValue: number;
      assumption?: string | null;
      confidence: "measured" | "estimated" | "illustrative";
    }[];
    currency?: string | null;
    qualitative?: string[];
    caveat?: string | null;
  };
  figures?: {
    type: string;
    heading?: string | null;
    caption?: string | null;
    [k: string]: unknown;
  }[];
  downloads?: {
    label: string;
    file: string;
  }[];
  reproduce: {
    repository?: string | null;
    commit: string;
    command?: string | null;
    dataSource?: "synthetic" | "public" | "client" | null;
    dataNote?: string | null;
    environment?: {
      [k: string]: unknown;
    } | null;
  };
  notes?: {
    whatWorked?: string | null;
    whatDidnt?: string | null;
    gotchas?: string[];
    nextTime?: string | null;
    timeSpentHours?: number | null;
  } | null;
}
export interface MetricEntry {
  name: string;
  unit: string;
  baseline: number;
  achieved: number;
  higherIsBetter: boolean;
  baselineSource: string;
}
