import type { NewsItem } from "../types/index.ts";
import { WEEKLY_BRIEF_FORMAT, type WeeklyBriefDocument } from "../lib/news/weeklyBrief.ts";

// Real weekly brief generated by scripts/generate_news.py from arXiv + market
// sources -- paper titles/abstracts spot-checked against arxiv.org before
// writing the literatureDeepDive section. All three sections (weeklyNews,
// selectedPapers, literatureDeepDive) and all three languages are filled in,
// matching the WeeklyBriefDocument schema NewsDetailPage expects.
const weeklyBrief2026W32: WeeklyBriefDocument = {
  format: WEEKLY_BRIEF_FORMAT,
  contentType: "html",
  translations: {
    "zh-TW": {
      title: "量子優化與機器學習新進展",
      summary: "本週精選五篇量子運算相關論文，並深入解析一項車隊協同路由的量子混合優化方法。",
      sections: {
        weeklyNews:
          "<p>本週的量子研究領域持續活躍，多篇新論文探討了量子優化、量子機器學習及量子錯誤更正等主題。</p>" +
          "<p>產業動態方面：</p>" +
          "<ul>" +
          "<li>IBM 與研究合作夥伴達成三項量子計算里程碑，顯示其在量子技術領域的持續進展（來源：富途牛牛）。</li>" +
          "<li>Oracle 在量子計算相關類股中領漲，反映市場對量子技術的關注（來源：Moomoo）。</li>" +
          "<li>Quantum Computing Inc.（QUBT.US）目標價維持在 22 美元，顯示市場對該公司的期待（來源：Moomoo）。</li>" +
          "</ul>" +
          "<p>下週值得關注的方向包括量子機器學習在實際應用中的進展，以及與傳統計算方法的比較。</p>",
        selectedPapers:
          "<ul>" +
          "<li><p><strong>Cooperative Platoon Routing and Dispatching via Edge-Assisted Hybrid Quantum Optimization</strong><br>提出邊緣輔助的閉環評估流程，將車隊協同路由問題轉換為 QUBO 表述，模擬顯示可降低自駕車隊 18.5% 的牽引能耗（來源：arXiv:2608.00524，尚未經同行審查）。</p></li>" +
          "<li><p><strong>Quantum machine learning interatomic potential: Application of variational quantum algorithm</strong><br>將量子電路學習應用於分子間位能的機器學習模型，以量子遷移學習重新訓練 ANI 模型，在特定條件下準確度略優於純古典模型（來源：arXiv:2607.27841，尚未經同行審查）。</p></li>" +
          "<li><p><strong>PACE-QAOA: Physics-Constrained Quantum Optimization for Qubit-Efficient Power System Islanding</strong><br>提出物理資訊編碼的混合量子優化方法，處理電網孤島劃分問題，於 8 個 IEEE 測試系統（9–89 匯流排）上驗證可行性（來源：arXiv:2608.02789，尚未經同行審查）。</p></li>" +
          "<li><p><strong>Oraqle: An Empirical Analysis of Qubit Readout and Discriminators in Quantum Error Correction</strong><br>分析量子錯誤更正中讀取（readout）與判別器對解碼效能的影響（來源：arXiv:2608.01939，尚未經同行審查）。</p></li>" +
          "<li><p><strong>Quantum annealers as programmable thermal machines</strong><br>將 D-Wave 量子退火機視為封閉熱力學循環，探討其運算過程中的能量交換行為（來源：arXiv:2608.04564，尚未經同行審查）。</p></li>" +
          "</ul>",
        literatureDeepDive:
          "<p><strong>本週精讀：Cooperative Platoon Routing and Dispatching via Edge-Assisted Hybrid Quantum Optimization</strong>（Talha Azfar, Ruimin Ke，arXiv:2608.00524，尚未經同行審查）</p>" +
          "<p>這篇論文處理自動駕駛車隊的節能路由問題：透過路側單元監測交通狀況，只在車流穩定的路段啟動車隊協同（platooning），並將路由決策表述為二元二次無約束優化（QUBO）問題，讓車輛間的交互作用能直接對應到量子伊辛模型（Ising）的耦合項。</p>" +
          "<p>在美國紐約州 Troy 市的模擬中，此方法相較於無協同的基準情境，減少了 <strong>18.5%</strong> 的車隊牽引能耗。作者也在 IBM 量子硬體上實測，發現採用鏈狀架構的 QAOA（Linear-Chain QAOA）相較於密集連接的 QAOA，可將雙量子位元 CNOT 閘的電路深度降低 <strong>66.7%</strong>，在淺電路深度下仍維持一定的最優解取樣成功率。</p>" +
          "<p>這篇論文的意義在於：結合邊緣運算的即時交通感知與淺層量子演算法，為近期量子硬體（NISQ 世代）在真實世界車隊調度場景中的應用，提供了一條可行的路徑。</p>",
      },
    },
    en: {
      title: "Advances in Quantum Optimization and Machine Learning",
      summary:
        "This week's brief covers five quantum computing papers, with a deep dive into a hybrid quantum approach to cooperative vehicle platoon routing.",
      sections: {
        weeklyNews:
          "<p>Quantum research remained active this week, with new papers spanning quantum optimization, quantum machine learning, and quantum error correction.</p>" +
          "<p>Industry highlights:</p>" +
          "<ul>" +
          "<li>IBM and research partners reached three quantum computing milestones, signaling continued progress in the field (source: Futu).</li>" +
          "<li>Oracle led gains among quantum-computing-related stocks, reflecting market interest in the technology (source: Moomoo).</li>" +
          "<li>Quantum Computing Inc. (QUBT.US) held a $22 price target, indicating continued market expectations for the company (source: Moomoo).</li>" +
          "</ul>" +
          "<p>Worth watching next week: how quantum machine learning progresses toward practical applications, and how it compares against classical approaches.</p>",
        selectedPapers:
          "<ul>" +
          "<li><p><strong>Cooperative Platoon Routing and Dispatching via Edge-Assisted Hybrid Quantum Optimization</strong><br>Formulates cooperative vehicle platoon routing as a QUBO problem with edge-assisted evaluation; simulations show an 18.5% reduction in fleet tractive-energy demand (source: arXiv:2608.00524, not yet peer-reviewed).</p></li>" +
          "<li><p><strong>Quantum machine learning interatomic potential: Application of variational quantum algorithm</strong><br>Applies quantum circuit learning to interatomic potentials, retraining the ANI model via quantum transfer learning with slightly higher accuracy under certain conditions (source: arXiv:2607.27841, not yet peer-reviewed).</p></li>" +
          "<li><p><strong>PACE-QAOA: Physics-Constrained Quantum Optimization for Qubit-Efficient Power System Islanding</strong><br>A physics-informed hybrid quantum optimization method for power-grid islanding, validated across 8 IEEE test systems from 9 to 89 buses (source: arXiv:2608.02789, not yet peer-reviewed).</p></li>" +
          "<li><p><strong>Oraqle: An Empirical Analysis of Qubit Readout and Discriminators in Quantum Error Correction</strong><br>Examines how qubit readout and discriminators affect decoder performance in quantum error correction (source: arXiv:2608.01939, not yet peer-reviewed).</p></li>" +
          "<li><p><strong>Quantum annealers as programmable thermal machines</strong><br>Frames D-Wave quantum annealers as a closed thermodynamic cycle and studies their energy-exchange behavior during computation (source: arXiv:2608.04564, not yet peer-reviewed).</p></li>" +
          "</ul>",
        literatureDeepDive:
          "<p><strong>This week's deep dive: Cooperative Platoon Routing and Dispatching via Edge-Assisted Hybrid Quantum Optimization</strong> (Talha Azfar, Ruimin Ke, arXiv:2608.00524, not yet peer-reviewed)</p>" +
          "<p>The paper tackles energy-efficient routing for autonomous vehicle fleets. Roadside units monitor traffic conditions and trigger cooperative platooning only on stable road segments, while the routing decision is formulated as a Quadratic Unconstrained Binary Optimization (QUBO) problem — letting vehicle-to-vehicle interactions map directly onto quantum Ising coupling terms.</p>" +
          "<p>In simulations for Troy, NY, the approach cut fleet tractive-energy demand by <strong>18.5%</strong> relative to a non-cooperative baseline. Testing on IBM quantum hardware, the authors found that a Linear-Chain QAOA circuit reduces two-qubit CNOT depth by <strong>66.7%</strong> compared with a dense QAOA layout, while still sampling optimal solutions at meaningful success rates at shallow circuit depths.</p>" +
          "<p>The takeaway: pairing edge-based traffic sensing with shallow quantum circuits offers a plausible path for near-term (NISQ-era) quantum hardware to support real-world autonomous fleet dispatch.</p>",
      },
    },
    fr: {
      title: "Avancées en optimisation quantique et apprentissage automatique",
      summary:
        "Cette semaine : cinq articles sur l'informatique quantique, avec une analyse approfondie d'une méthode hybride quantique pour le routage coopératif de pelotons de véhicules.",
      sections: {
        weeklyNews:
          "<p>La recherche quantique est restée active cette semaine, avec de nouveaux articles couvrant l'optimisation quantique, l'apprentissage automatique quantique et la correction d'erreurs quantiques.</p>" +
          "<p>Actualités du secteur :</p>" +
          "<ul>" +
          "<li>IBM et ses partenaires de recherche ont franchi trois étapes importantes en informatique quantique, signe de progrès continus dans le domaine (source : Futu).</li>" +
          "<li>Oracle a mené les gains parmi les actions liées à l'informatique quantique, reflétant l'intérêt du marché pour cette technologie (source : Moomoo).</li>" +
          "<li>Quantum Computing Inc. (QUBT.US) maintient un objectif de cours de 22 $, signe des attentes persistantes du marché envers l'entreprise (source : Moomoo).</li>" +
          "</ul>" +
          "<p>À surveiller la semaine prochaine : les progrès de l'apprentissage automatique quantique vers des applications concrètes, et sa comparaison avec les approches classiques.</p>",
        selectedPapers:
          "<ul>" +
          "<li><p><strong>Cooperative Platoon Routing and Dispatching via Edge-Assisted Hybrid Quantum Optimization</strong><br>Formule le routage coopératif de pelotons de véhicules comme un problème QUBO assisté par le edge computing ; les simulations montrent une réduction de 18,5 % de la demande énergétique de traction de la flotte (source : arXiv:2608.00524, non encore relu par les pairs).</p></li>" +
          "<li><p><strong>Quantum machine learning interatomic potential: Application of variational quantum algorithm</strong><br>Applique l'apprentissage par circuit quantique aux potentiels interatomiques, en réentraînant le modèle ANI via l'apprentissage par transfert quantique, avec une précision légèrement supérieure dans certaines conditions (source : arXiv:2607.27841, non encore relu par les pairs).</p></li>" +
          "<li><p><strong>PACE-QAOA: Physics-Constrained Quantum Optimization for Qubit-Efficient Power System Islanding</strong><br>Une méthode hybride d'optimisation quantique informée par la physique pour l'îlotage des réseaux électriques, validée sur 8 systèmes de test IEEE de 9 à 89 jeux de barres (source : arXiv:2608.02789, non encore relu par les pairs).</p></li>" +
          "<li><p><strong>Oraqle: An Empirical Analysis of Qubit Readout and Discriminators in Quantum Error Correction</strong><br>Examine l'effet de la lecture des qubits et des discriminateurs sur la performance du décodage en correction d'erreurs quantiques (source : arXiv:2608.01939, non encore relu par les pairs).</p></li>" +
          "<li><p><strong>Quantum annealers as programmable thermal machines</strong><br>Présente les recuiteurs quantiques D-Wave comme un cycle thermodynamique fermé et étudie leur comportement d'échange d'énergie pendant le calcul (source : arXiv:2608.04564, non encore relu par les pairs).</p></li>" +
          "</ul>",
        literatureDeepDive:
          "<p><strong>Analyse de la semaine : Cooperative Platoon Routing and Dispatching via Edge-Assisted Hybrid Quantum Optimization</strong> (Talha Azfar, Ruimin Ke, arXiv:2608.00524, non encore relu par les pairs)</p>" +
          "<p>Cet article s'attaque au routage économe en énergie pour les flottes de véhicules autonomes. Des unités en bordure de route surveillent les conditions de circulation et n'activent le peloton coopératif que sur des tronçons stables, tandis que la décision de routage est formulée comme un problème d'optimisation binaire quadratique sans contrainte (QUBO) — permettant aux interactions entre véhicules de correspondre directement aux termes de couplage d'Ising quantique.</p>" +
          "<p>Dans des simulations pour Troy, NY, l'approche a réduit la demande énergétique de traction de la flotte de <strong>18,5 %</strong> par rapport à une base sans coopération. Testée sur du matériel quantique IBM, elle montre qu'un circuit QAOA en chaîne linéaire réduit la profondeur des portes CNOT à deux qubits de <strong>66,7 %</strong> par rapport à un QAOA dense, tout en échantillonnant des solutions optimales avec des taux de succès significatifs à faible profondeur de circuit.</p>" +
          "<p>À retenir : combiner la perception du trafic en périphérie avec des circuits quantiques peu profonds offre une voie plausible pour que le matériel quantique actuel (ère NISQ) soutienne le déploiement réel de flottes autonomes.</p>",
      },
    },
  },
};

export const news: NewsItem[] = [
  {
    slug: "weekly-quantum-news-2026-w32",
    date: "2026-08-06",
    category: "Research Update",
    title: weeklyBrief2026W32.translations["zh-TW"].title,
    summary: weeklyBrief2026W32.translations["zh-TW"].summary,
    content: JSON.stringify(weeklyBrief2026W32),
    coverImageUrl: null,
    relatedProjectSlug: null,
    relatedPublicationSlug: null,
    externalUrl: null,
  },
];
